### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by roxy13heart**
There is no version '0.4.1'.  I think you meant '0.3.1'.

### CODE REVIEW

**Comment by tim-evans** [comment]
@roxy13heart I'm bad at tagging my releases. I'll go back and tag releases for the past few versions.

**Comment by roxy13heart** [comment]
Ok.  I'll delete my branch.

**Comment by tim-evans** [comment]
Thanks!

**Comment by roxy13heart** [comment]
Also I would like to see features like minWidth and minHeight to set the initial dimensions of the text area.   I see a "rows" option, but I don't think that's what I'm looking for.

**Pull request closed without merging**
