### PR TITLE
Package Updates

### PR DESCRIPTION
**Pull request by elwayman02**
Took the defaults from ember init for ember-cli 0.2.3 and then scaled back the changes that overwrote stuff we would want to keep.

Also expanded the README quite a bit.

Intending to put the max-width/max-height changes in for 0.4.0, so don't release a new version just yet.  Figured with this many package changes it warranted a version bump.

### CODE REVIEW

**Comment by tim-evans** [comment]
I think this only warrants a patch. It's really just a documentation and updates to the installation. Could you change the version number to `0.3.7`?

When we add the code for units, then I'll bump to `0.4.0`. :)

**Comment by elwayman02** [comment]
:+1:

**Comment by elwayman02** [comment]
@tim-evans done.

**Comment by tim-evans** [comment]
I'm going to do a little work on this tonight, including the upgrade to ember 1.12.0, ember-cli 0.2.4, and units on sizes

**Pull request merged**
